env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
globals:
  PICTURES: false
rules:
  comma-dangle:
    - error
    - always-multiline
  react/jsx-uses-vars: error
  react/jsx-uses-react: error
  no-console: warn
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
